// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qraxvdhsusmwbtztavzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyYXh2ZGhzdXNtd2J0enRhdnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzUyNzMsImV4cCI6MjA3MTIxMTI3M30.yBtB3VBTCut9pVa8qh6VzCr0Hc8-vKApocfaYBwU5A4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});